<?php

/*
 * This file is generated by S. Das.
 * Do not copy it without permission.
 */
//Contact at: tapan84silchar[at]gmail.com
define("HOST11", "http://172.16.25.158/multimedia_portal");
define("DB_HOST", "172.16.25.158");
define("USERNAME", "root");
define("PASS", "software");
define("DBNAME", "multimedia_portal");
define("HOSTNAME", "172.16.25.158");
?>
